
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Peut être "create", "update", "validate", ou "none"
    show-sql: true      # Pour afficher les requêtes SQL dans la console
    properties:
      hibernate:
        format_sql: true